### ISSUE TITLE
Dialogue box

### ISSUE THREAD

**Issue by Nessiah** [Nessiah/Frogivera#5]
Dialogue box with nice text typing and scrolling. (Maybe moving character sprite?)

**Comment by BotsBotsBotsBots** [comment]
Not sure about the moving sprites bit, seems a bit advanced. Even eye blinks were rare in gbc days

**Comment by Nessiah** [comment]
They were still technically possible back then, though. Guess this raises a question of whether we're going with "a game emulating gbc games" or "a game emulating gbc limitations". Nothing stops us from making a "technically advanced" gbc-like game.

**Comment by BotsBotsBotsBots** [comment]
Well, it's technically also possible to show like, a thousand colours on the GBC by swapping palettes mid-scanline, but that wouldn't really Feel a gbc game, visually. So let's go with limitations, at least where it can add to the feel in a way that's not negative. Like, let's not do any sprite flickering, that looks terrible.
