### ISSUE TITLE
Ability Buttons

### ISSUE THREAD

**Issue by BotsBotsBotsBots** [Nessiah/Frogivera#6]
Figure out if the Dos Button look should stay, make sure all the information the player needs is easily available. Different overall button colours based on Combo Element colour?

**Comment by Nessiah** [comment]
Right now the button change is done just by smooth fading out and back in. What would be the gbc-like way to do that?

**Comment by BotsBotsBotsBots** [comment]
I guess it'd have to be a series of frames, doesn't even have to be more than like, two extra frames between one state and the other.

**Comment by BotsBotsBotsBots** [comment]
This issue has been merged into #27
